#!/usr/bin/env bash
# installs and configures nginx

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4$^/redirect_me;' /etc/nginx/sites-available/default
service nginx restart
