#!/usr/bin/env bash
# Configures a new Ubuntu server with an HAproxy load balancer
apt-get update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y install haproxy=2.6.\*

INIT_FILE='/etc/default/haproxy'
CONFIG_FILE='/etc/haproxy/haproxy.cfg'
HAPROXY_LB_CONFIG="\
listen thejob
	mode http
	bind :80
	balance roundrobin
	server 23482-web-01 3.229.117.173:80 check
	server 23482-web-02 18.206.16.182:80 check
"
# Create files if they don't already exist
[ -f "$INIT_FILE" ] || touch "$INIT_FILE"
[ -f "$CONFIG_FILE" ] || touch "$CONFIG_FILE"

# Make sure that HAproxy can be managed via an init script
if [ "$(grep -Eco '^ENABLED=[01]$' < $INIT_FILE)" -gt 0 ]; then
	sed -i 's/^ENABLED=0$/ENABLED=1/' "$INIT_FILE"
else
	echo 'ENABLED=1' >> $INIT_FILE
fi

# Insert new HAproxy configuration directives into config file
echo "$HAPROXY_LB_CONFIG" >> "$CONFIG_FILE"

# Start HAproxy, or restart if already running
if [ "$(pgrep -c haproxy)" -le 0 ]; then
	service haproxy start
else
	service haproxy restart
fi
