#!/usr/bin/env bash
# A bash script demonstrating a while loop

i=1
while [ $i -le 10 ]
do
	if [ $((i%4)) == 0 ] && [ $((i%8)) != 0 ]; then
		echo "bad luck"
	elif [ $((i%8)) == 0 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(( i + 1 ))
done
