#!/usr/bin/env bash
# Displays all active IPv4 IPs on the machine it's executed on
# Method 1
#ip -4 -br address | grep -oE '([0-9]+\.?){4}'
# Method 2
ifconfig | grep -oE 'inet [0-9]+(\.[0-9]+){3}' | cut -f2 -d ' '
